// examples/enum-based/src/main.tsx
import { PermixProvider } from 'permix/react'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import { permix } from './lib/permix'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <PermixProvider permix={permix}>
      <App />
    </PermixProvider>
  </StrictMode>,
)

// examples/solid/src/index.tsx
import { PermixProvider } from 'permix/solid'
import { render } from 'solid-js/web'
/* @refresh reload */
import App from './App.tsx'
import { permix } from './lib/permix'
import './index.css'

const root = document.getElementById('root')

render(() => (
  <PermixProvider permix={permix}>
    <App />
  </PermixProvider>
), root!)
